apiVersion: v2
name: helm-es-operator
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for ECK

dependencies:
  - name: eck-operator
    version: "2.3.0"
    repository: "https://helm.elastic.co"
    condition: eck-operator.enabled
