apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: google-oidc-secret
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: google-oidc-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "GOOGLE_CLIENT_ID"
      remoteRef:
        key: gke-devops-oidc
        version: latest
        property: GOOGLE_CLIENT_ID

    - secretKey: "GOOGLE_CLIENT_SECRET"
      remoteRef:
        key: gke-devops-oidc
        version: latest
        property: GOOGLE_CLIENT_SECRET
