apiVersion: v2
name: helm-nginx-ingress
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Nginx Ingress

dependencies:
  - name: ingress-nginx
    version: "4.1.4"
    repository: "https://kubernetes.github.io/ingress-nginx/"
    condition: ingress-nginx.enabled
