apiVersion: v2
name: helm-sftp
description: A Helm chart for sftp

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: "generic-app"
    alias: sftp-gcs
    condition: sftp-gcs.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"
