---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing-1
  annotations:
    networking.gke.io/managed-certificates: managed-cert-aldamex-thailand
    kubernetes.io/ingress.allow-http: 'true'
    kubernetes.io/ingress.global-static-ip-name: gke-ingress-1
spec:
  tls:
    - secretName: nginx-cert
    - secretName: nginx-cert-admx
    - secretName: nginx-cert-napbiotec
    - secretName: nginx-cert-napbiotec-com
    - secretName: nginx-cert-genuine-napbiotec-io
  rules:
    - host: '*.{{ .Values.domain }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '*.{{ .Values.domain2 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '{{ .Values.domain2 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443

    # Place aldamexthailand.com befor aldamex.com
    - host: '*.{{ .Values.domain7 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '{{ .Values.domain7 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443

    - host: '*.{{ .Values.domain3 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '{{ .Values.domain3 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '*.{{ .Values.domain4 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '{{ .Values.domain4 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '{{ .Values.domain5 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
    - host: '{{ .Values.domain6 }}'
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.backendService }}
                port:
                  number: 443
