apiVersion: v2
name: helm-genuine
description: A Helm chart for genuine

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  - name: "generic-app"
    alias: generic-app
    condition: generic-app.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"
